remote_theme: nandomoreirame/end2end/source
title: League of Science Superfriends
description: Covering all the latest on Covid Immunobiology!

author:
  name: League of Science Superfriends
  thumb: https://pbs.twimg.com/profile_images/1390118029401411584/t9S6LqkQ_200x200.jpg
  email: sciencesuperfriends@gmail.com
  url: https://lsuperfriends.github.io/
  github: https://github.com/lsuperfriends
  twitter: https://twitter.com/lsuperfriends
  facebook: https://www.facebook.com/leagueofscience/
  
navbar:
  - slug: about
    title: About
  - slug: posts
    title: Posts
