theme: jekyll-theme-cayman
title: League of Science Superfriends
description: Covering all the latest on Covid Immunobiology!
twitter:
  username: lsuperfriends
facebook: leagueofscience
  
header_page_refs: ['about', 'contact']
